import type { Translations } from '~/types';

/**
 * Locally-owned UI strings, keyed by locale.
 * Resolution in the store's `t(key)`: jw.org API translation → this dictionary
 * for the active locale → the `en` entry → the key itself.
 *
 * `en` is the fallback of last resort and MUST stay complete: several keys here
 * (lnkSearch, btnDownload, hdgSubtitles, btnPlay, btnPlayWith(out)Subtitles,
 * lnkHome, searchResultsCountText, noSearchResultsText, refineSearchResultsText)
 * are also real jw.org translation keys, so they normally resolve from the
 * fetched translations at runtime — but if that fetch fails, `en` is all that's
 * left. Every other locale block therefore only needs the strings jw.org does
 * NOT provide: the bespoke shell copy + the three search sort labels (taken
 * verbatim from the search API so the pre-query dropdown matches post-query).
 * Add a locale block to translate the app shell into a new language.
 */
export const uiStrings: Record<string, Translations> = {
  en: {
    guide: 'Guide',
    lnkSearch: 'Search',
    searchPlaceholder: 'Search or paste jw.org link...',
    searchFailed: 'Search failed. Please try again later.',
    loadFailed: 'Loading failed. Please try again later.',
    castFailed: 'Casting failed. Please try again.',
    retry: 'Retry',
    noTranscript: 'No transcript available',
    noResults: 'No results',
    searchResultsCountText: 'Showing %1$s of %2$s',
    noSearchResultsText: 'Sorry, no results. Please check your spelling or enter different search words.',
    refineSearchResultsText: 'Enter additional words to narrow down your search.',
    sortRelevance: 'Relevance',
    sortNewest: 'Newest',
    sortOldest: 'Oldest',
    transcript: 'Transcript',
    chromecast: 'Chromecast',
    btnDownload: 'Download',
    hdgSubtitles: 'Subtitles',
    lnkHome: 'jw.org',
    btnPlay: 'Play',
    btnPlayWithSubtitles: 'Play with subtitles',
    btnPlayWithoutSubtitles: 'Play without subtitles',
  },
  nl: {
    guide: 'Handleiding',
    searchPlaceholder: 'Zoek of plak jw.org link...',
    searchFailed: 'Zoeken is mislukt. Probeer het later opnieuw.',
    loadFailed: 'Laden is mislukt. Probeer het later opnieuw.',
    castFailed: 'Casten is mislukt. Probeer het opnieuw.',
    retry: 'Opnieuw proberen',
    noTranscript: 'Geen transcript beschikbaar',
    noResults: 'Geen resultaten',
    transcript: 'Transcript',
    sortRelevance: 'Relevantie',
    sortNewest: 'Nieuwste',
    sortOldest: 'Oudste',
  },
  es: {
    guide: 'Guía',
    searchPlaceholder: 'Busca o pega un enlace de jw.org...',
    searchFailed: 'La búsqueda falló. Inténtalo de nuevo más tarde.',
    loadFailed: 'Error al cargar. Inténtalo de nuevo más tarde.',
    castFailed: 'Error al transmitir. Inténtalo de nuevo.',
    retry: 'Reintentar',
    noTranscript: 'No hay transcripción disponible',
    noResults: 'Sin resultados',
    transcript: 'Transcripción',
    sortRelevance: 'coincidencia',
    sortNewest: 'más recientes',
    sortOldest: 'menos recientes',
  },
  pt: {
    guide: 'Guia',
    searchPlaceholder: 'Pesquise ou cole um link do jw.org...',
    searchFailed: 'A pesquisa falhou. Tente novamente mais tarde.',
    loadFailed: 'Falha ao carregar. Tente novamente mais tarde.',
    castFailed: 'Falha na transmissão. Tente novamente.',
    retry: 'Tentar de novo',
    noTranscript: 'Nenhuma transcrição disponível',
    noResults: 'Nenhum resultado',
    transcript: 'Transcrição',
    sortRelevance: 'Relevância',
    sortNewest: 'Mais recentes',
    sortOldest: 'Mais antigos',
  },
  fr: {
    guide: 'Guide',
    searchPlaceholder: 'Recherchez ou collez un lien jw.org...',
    searchFailed: 'Échec de la recherche. Réessayez plus tard.',
    loadFailed: 'Échec du chargement. Réessayez plus tard.',
    castFailed: 'Échec de la diffusion. Réessayez.',
    retry: 'Réessayer',
    noTranscript: 'Aucune transcription disponible',
    noResults: 'Aucun résultat',
    transcript: 'Transcription',
    sortRelevance: 'Pertinence',
    sortNewest: 'Les + récents',
    sortOldest: 'Les + anciens',
  },
  de: {
    guide: 'Anleitung',
    searchPlaceholder: 'Suchen oder jw.org-Link einfügen...',
    searchFailed: 'Suche fehlgeschlagen. Bitte später erneut versuchen.',
    loadFailed: 'Laden fehlgeschlagen. Bitte später erneut versuchen.',
    castFailed: 'Streamen fehlgeschlagen. Bitte erneut versuchen.',
    retry: 'Erneut versuchen',
    noTranscript: 'Kein Transkript verfügbar',
    noResults: 'Keine Ergebnisse',
    transcript: 'Transkript',
    sortRelevance: 'Relevanz',
    sortNewest: 'Neueste zuerst',
    sortOldest: 'Älteste zuerst',
  },
  it: {
    guide: 'Guida',
    searchPlaceholder: 'Cerca o incolla un link di jw.org...',
    searchFailed: 'Ricerca non riuscita. Riprova più tardi.',
    loadFailed: 'Caricamento non riuscito. Riprova più tardi.',
    castFailed: 'Trasmissione non riuscita. Riprova.',
    retry: 'Riprova',
    noTranscript: 'Nessuna trascrizione disponibile',
    noResults: 'Nessun risultato',
    transcript: 'Trascrizione',
    sortRelevance: 'Rilevanza',
    sortNewest: 'dal più recente',
    sortOldest: 'dal meno recente',
  },
  ja: {
    guide: 'ガイド',
    searchPlaceholder: '検索、または jw.org のリンクを貼り付け...',
    searchFailed: '検索に失敗しました。後でもう一度お試しください。',
    loadFailed: '読み込みに失敗しました。後でもう一度お試しください。',
    castFailed: 'キャストに失敗しました。もう一度お試しください。',
    retry: '再試行',
    noTranscript: 'トランスクリプトはありません',
    noResults: '結果がありません',
    transcript: 'トランスクリプト',
    sortRelevance: '関連度',
    sortNewest: '新しい順',
    sortOldest: '古い順',
  },
  ko: {
    guide: '가이드',
    searchPlaceholder: '검색하거나 jw.org 링크를 붙여넣으세요...',
    searchFailed: '검색에 실패했습니다. 나중에 다시 시도해 주세요.',
    loadFailed: '불러오기에 실패했습니다. 나중에 다시 시도해 주세요.',
    castFailed: '전송에 실패했습니다. 다시 시도해 주세요.',
    retry: '다시 시도',
    noTranscript: '대본을 사용할 수 없습니다',
    noResults: '결과 없음',
    transcript: '대본',
    sortRelevance: '관련성',
    sortNewest: '최근 항목순',
    sortOldest: '오래된 항목순',
  },
  ru: {
    guide: 'Руководство',
    searchPlaceholder: 'Поиск или вставьте ссылку jw.org...',
    searchFailed: 'Ошибка поиска. Повторите попытку позже.',
    loadFailed: 'Ошибка загрузки. Повторите попытку позже.',
    castFailed: 'Не удалось начать трансляцию. Повторите попытку.',
    retry: 'Повторить',
    noTranscript: 'Расшифровка недоступна',
    noResults: 'Нет результатов',
    transcript: 'Расшифровка',
    sortRelevance: 'по релевантности',
    sortNewest: 'сначала новые',
    sortOldest: 'сначала старые',
  },
  pl: {
    guide: 'Przewodnik',
    searchPlaceholder: 'Wyszukaj lub wklej link jw.org...',
    searchFailed: 'Wyszukiwanie nie powiodło się. Spróbuj ponownie później.',
    loadFailed: 'Ładowanie nie powiodło się. Spróbuj ponownie później.',
    castFailed: 'Przesyłanie nie powiodło się. Spróbuj ponownie.',
    retry: 'Spróbuj ponownie',
    noTranscript: 'Brak dostępnej transkrypcji',
    noResults: 'Brak wyników',
    transcript: 'Transkrypcja',
    sortRelevance: 'Trafność',
    sortNewest: 'od najnowszych',
    sortOldest: 'od najstarszych',
  },
  tl: {
    guide: 'Gabay',
    searchPlaceholder: 'Maghanap o mag-paste ng link ng jw.org...',
    searchFailed: 'Nabigo ang paghahanap. Subukan ulit mamaya.',
    loadFailed: 'Nabigo ang pag-load. Subukan ulit mamaya.',
    castFailed: 'Nabigo ang pag-cast. Subukan ulit.',
    retry: 'Subukan ulit',
    noTranscript: 'Walang available na transcript',
    noResults: 'Walang resulta',
    transcript: 'Transkripsiyon',
    sortRelevance: 'Pinakamalapit',
    sortNewest: 'Pinakabago',
    sortOldest: 'Pinakaluma',
  },
  cmn_hans: {
    guide: '指南',
    searchPlaceholder: '搜索或粘贴 jw.org 链接...',
    searchFailed: '搜索失败。请稍后再试。',
    loadFailed: '加载失败。请稍后再试。',
    castFailed: '投放失败。请重试。',
    retry: '重试',
    noTranscript: '没有可用的文字记录',
    noResults: '没有结果',
    transcript: '文字记录',
    sortRelevance: '相关资料',
    sortNewest: '最新',
    sortOldest: '最旧',
  },
  da: {
    guide: 'Vejledning',
    searchPlaceholder: 'Søg eller indsæt et jw.org-link...',
    searchFailed: 'Søgningen mislykkedes. Prøv igen senere.',
    loadFailed: 'Indlæsningen mislykkedes. Prøv igen senere.',
    castFailed: 'Casting mislykkedes. Prøv igen.',
    retry: 'Prøv igen',
    noTranscript: 'Ingen udskrift tilgængelig',
    noResults: 'Ingen resultater',
    transcript: 'Udskrift',
    sortRelevance: 'Relevans',
    sortNewest: 'Nyeste',
    sortOldest: 'Ældste',
  },
  fi: {
    guide: 'Opas',
    searchPlaceholder: 'Hae tai liitä jw.org-linkki...',
    searchFailed: 'Haku epäonnistui. Yritä myöhemmin uudelleen.',
    loadFailed: 'Lataus epäonnistui. Yritä myöhemmin uudelleen.',
    castFailed: 'Lähetys epäonnistui. Yritä uudelleen.',
    retry: 'Yritä uudelleen',
    noTranscript: 'Tekstiversiota ei ole saatavilla',
    noResults: 'Ei tuloksia',
    transcript: 'Tekstiversio',
    sortRelevance: 'Vastaavuus',
    sortNewest: 'Uusin',
    sortOldest: 'Vanhin',
  },
};
